#!/bin/bash

defaultcolor="\033[m"
colors=("\033[1m" "\033[30m" "\033[31m" "\033[32m" 
"\033[33m" "\033[34m" "\033[35m" "\033[36m" "\033[37m" "\033[1;30m" "\033[1;31m" "\033[1;32m" "\033[1;33m" "\033[1;34m" "\033[1;35m" "\033[1;36m")

numberofcolors=${#colors[@]}

for int in `seq 1 100000`;
	do
		colorindex=$((int % $numberofcolors))
		numberoffolds=$((($int % 70) + 1))
		var=`cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w $numberoffolds | head -n 1`
		echo -e "${colors[$colorindex]}$var"
		echo -e -n "\033[m"
		echo -e -n "\a"
		sleep 1
	done
